/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaModelo.Compra;
import CapaModelo.Proveedor;
import CapaModelo.Usuario;
import CapaNegocio.ComprasService;
import CapaNegocio.ProveedorService;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//PRUEBA PARA VER SI CARGA BIEN 
// nueva prueba 

/**
 *
 * @author adoni
 */
public class Compras extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Usuario usuarioLogueado;

    public Compras(Usuario usuario) {
        initComponents();
        this.usuarioLogueado = usuario;
        cargarProveedores();
        cargarTabla();
        limpiarCampos();
        txtId.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        BtnVolverMenú = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnRegistrar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        cbProveedor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Icono MiniSuper.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 1370, 130));

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Gestión Compras");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 450, 43));

        jLabel3.setBackground(new java.awt.Color(0, 102, 204));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Id Compra: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 160, 50));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 245, 1080, -1));
        jPanel1.add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 260, 35));

        jLabel6.setBackground(new java.awt.Color(0, 102, 204));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Proveedor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 150, 30));
        jPanel1.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 260, 35));

        jLabel7.setBackground(new java.awt.Color(0, 102, 204));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Nombre producto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 260, 43));

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Compra", "Fecha", "Nombre Producto", "Cantidad", "Precio Compra", "Proveedor"
            }
        ));
        tablaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProveedores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 1270, 200));

        BtnVolverMenú.setBackground(new java.awt.Color(255, 0, 0));
        BtnVolverMenú.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnVolverMenú.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolverMenú.setText("Volver a Menú");
        BtnVolverMenú.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverMenúActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVolverMenú, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 183, -1));

        BtnModificar.setBackground(new java.awt.Color(255, 204, 0));
        BtnModificar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificar.setText("Actualizar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 190, -1));

        BtnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        BtnEliminar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 640, 183, -1));

        BtnRegistrar.setBackground(new java.awt.Color(0, 204, 0));
        BtnRegistrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, 183, -1));

        txtId.setBackground(new java.awt.Color(204, 204, 204));
        txtId.setText("No es necesario insertar un ID");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 260, 35));

        jLabel8.setBackground(new java.awt.Color(0, 102, 204));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Cantidad: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, 30));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 260, 35));

        cbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 260, 40));

        jLabel9.setBackground(new java.awt.Color(0, 102, 204));
        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Precio Compra:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverMenúActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverMenúActionPerformed

        boolean hayDatos = !txtProducto.getText().trim().isEmpty()
                || !txtCantidad.getText().trim().isEmpty()
                || !txtPrecioCompra.getText().trim().isEmpty();

        int cri;

        if (hayDatos) {
            cri = JOptionPane.showConfirmDialog(
                    null,
                    "¿Realmente desea volver?\nAún no termina de agregar la compra.",
                    "Advertencia",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            cri = JOptionPane.showConfirmDialog(
                    null,
                    "¿Desea volver al menú?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );
        }

        if (cri == JOptionPane.YES_OPTION) {
            Principal p = new Principal(usuarioLogueado);
            p.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_BtnVolverMenúActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // Supongamos que tu JTable se llama tblCompras
        int fila = tablaProveedores.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para actualizar");
            return;
        }

// Tomamos el IdCompra de la columna que contiene el ID (suponiendo que es la columna 0)
        int idCompra = Integer.parseInt(tablaProveedores.getValueAt(fila, 0).toString());

// Creamos el objeto Compra con todos los datos del formulario
        Compra c = new Compra();
        c.setIdCompra(idCompra); // 🔥 Aquí estaba el problema
        c.setNombreProducto(txtProducto.getText());
        c.setCantidad(Integer.parseInt(txtCantidad.getText()));
        c.setPrecioCompra(Double.parseDouble(txtPrecioCompra.getText()));
        c.setProveedor(cbProveedor.getSelectedItem().toString());

// Llamamos a actualizar
        ComprasService service = new ComprasService();
        boolean actualizado = service.actualizarCompra(c);
        if (actualizado) {
            JOptionPane.showMessageDialog(this, "Compra actualizada correctamente");
            cargarTabla();
            limpiarCampos();
            ;
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar la compra");
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed

        if (tablaProveedores.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una compra de la tabla");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea eliminar esta compra?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {

            ComprasService service = new ComprasService();

            Compra c = new Compra();
            c.setIdCompra(Integer.parseInt(txtId.getText())); // 🔥 PRIMARY KEY

            boolean eliminado = service.eliminarCompra(c.getIdCompra());

            if (eliminado) {
                JOptionPane.showMessageDialog(this, "Compra eliminada correctamente");

                cargarTabla();
                limpiarCampos();
                // 🔥 volvemos a habilitar
                // 🔥 refresca JTable

            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
        }


    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed

        try {
            ComprasService service = new ComprasService();
            Compra c = new Compra();

            // 📅 Fecha actual automática
            c.setFecha(new java.util.Date());

            c.setNombreProducto(txtProducto.getText());
            c.setCantidad(Integer.parseInt(txtCantidad.getText()));
            c.setPrecioCompra(Double.parseDouble(txtPrecioCompra.getText()));

            // 🔽 Proveedor desde ComboBox
            c.setProveedor(cbProveedor.getSelectedItem().toString());

            boolean registrado = service.insertar(c);

            if (registrado) {
                JOptionPane.showMessageDialog(this, "Compra registrada correctamente");
                limpiarCampos();
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar la compra");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Cantidad y Precio deben ser números válidos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar la compra");
        }


    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void tablaProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedoresMouseClicked
        int fila = tablaProveedores.getSelectedRow();

        if (fila >= 0) {
            txtId.setText(tablaProveedores.getValueAt(fila, 0).toString());

            txtProducto.setText(tablaProveedores.getValueAt(fila, 2).toString());

            txtCantidad.setText(tablaProveedores.getValueAt(fila, 3).toString());

            txtPrecioCompra.setText(tablaProveedores.getValueAt(fila, 4).toString());

            cbProveedor.setSelectedItem(tablaProveedores.getValueAt(fila, 5).toString());

            txtId.setEditable(false);

        }
    }//GEN-LAST:event_tablaProveedoresMouseClicked

    private void limpiarCampos() {
        txtId.setText("No es necesario insertar un ID");
        txtProducto.setText("");

        txtPrecioCompra.setText("");
        txtCantidad.setText("");
        cbProveedor.setSelectedIndex(0);
        txtId.setForeground(Color.GRAY);

    }

    private void cargarTabla() {
        ComprasService service = new ComprasService();
        List<Compra> lista = service.listarCompra();

        DefaultTableModel modelo = (DefaultTableModel) tablaProveedores.getModel();
        modelo.setRowCount(0); // limpia la tabla

        for (Compra c : lista) {
            modelo.addRow(new Object[]{
                c.getIdCompra(),
                c.getFecha(),
                c.getNombreProducto(),
                c.getCantidad(),
                c.getPrecioCompra(),
                c.getProveedor()
            }
            );
        }
    }

    private void cargarProveedores() {

        ProveedorService service = new ProveedorService();
        List<String> lista = service.listarNombres();

        cbProveedor.removeAllItems(); // limpiar antes

        for (String nombre : lista) {
            cbProveedor.addItem(nombre);
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnVolverMenú;
    private javax.swing.JComboBox<String> cbProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
