/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaDatos.ComprasDAO;
import CapaModelo.Compra;
import CapaModelo.Proveedor;
import CapaModelo.Usuario;
import CapaNegocio.ComprasService;
import CapaNegocio.ProveedorService;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import CapaModelo.Producto;
import CapaModelo.Usuario;
import CapaNegocio.ProductoService;
import CapaNegocio.VentaService;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.LineSeparator;
import java.awt.Desktop;
import java.io.FileOutputStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
//PRUEBA PARA VER SI CARGA BIEN 
// nueva prueba 

/**
 *
 * @author adoni
 */
public class Compras extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Usuario usuarioLogueado;

    public Compras(Usuario usuario) {
        initComponents();
        this.usuarioLogueado = usuario;
        cargarProveedores();

        limpiarCampos();
        inicializarTabla();
        eventoActivado = true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        BtnVolverMenú = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        BtnRegistrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        cbProveedor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Icono MiniSuper.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 1370, 130));

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Gestión Compras");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 450, 43));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 245, 1080, -1));
        jPanel1.add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 260, 35));

        jLabel6.setBackground(new java.awt.Color(0, 102, 204));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Proveedor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 150, 30));
        jPanel1.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 260, 35));

        jLabel7.setBackground(new java.awt.Color(0, 102, 204));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Nombre producto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 250, 30));

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Proveedor"
            }
        ));
        tablaCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCompras);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 1270, 200));

        BtnVolverMenú.setBackground(new java.awt.Color(255, 0, 0));
        BtnVolverMenú.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnVolverMenú.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolverMenú.setText("Volver a Menú");
        BtnVolverMenú.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverMenúActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVolverMenú, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 183, -1));

        BtnAgregar.setBackground(new java.awt.Color(0, 204, 0));
        BtnAgregar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("+ Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 370, 183, -1));

        BtnRegistrar.setBackground(new java.awt.Color(0, 102, 0));
        BtnRegistrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("Registrar compra");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1003, 640, 300, -1));

        jLabel8.setBackground(new java.awt.Color(0, 102, 204));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Cantidad: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, 30));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 260, 35));

        cbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbProveedorMouseClicked(evt);
            }
        });
        cbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(cbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 260, 40));

        jLabel9.setBackground(new java.awt.Color(0, 102, 204));
        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Precio Compra:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 230, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/icono usuario.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 40, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Logo precio icono.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 40, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Logo productos icono.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 40, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Logo Cantidad.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean cargandoProveedores = true;
    DefaultTableModel modelo;
    private boolean eventoActivado = false;

    private void inicializarTabla() {

        modelo = new DefaultTableModel();

        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        modelo.addColumn("Proveedor");

        tablaCompras.setModel(modelo);
    }


    private void BtnVolverMenúActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverMenúActionPerformed

        boolean hayDatos = !txtProducto.getText().trim().isEmpty()
                || !txtCantidad.getText().trim().isEmpty()
                || !txtPrecioCompra.getText().trim().isEmpty();

        int cri;

        if (hayDatos) {
            cri = JOptionPane.showConfirmDialog(
                    null,
                    "¿Realmente desea volver?\nAún no termina de agregar la compra.",
                    "Advertencia",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            cri = JOptionPane.showConfirmDialog(
                    null,
                    "¿Desea volver al menú?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );
        }

        if (cri == JOptionPane.YES_OPTION) {
            Principal p = new Principal(usuarioLogueado);
            p.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_BtnVolverMenúActionPerformed


    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed

        // 🔥 VALIDAR proveedor correctamente
        if (cbProveedor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un proveedor válido");
            return;
        }

        String producto = txtProducto.getText();

        if (producto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese nombre del producto");
            return;
        }

        int cantidad;
        double precio;

        try {
            cantidad = Integer.parseInt(txtCantidad.getText());
            precio = Double.parseDouble(txtPrecioCompra.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cantidad o precio inválido");
            return;
        }

        String proveedor = cbProveedor.getSelectedItem().toString();

        modelo.addRow(new Object[]{
            producto,
            cantidad,
            precio,
            proveedor
        });

        txtProducto.setText("");
        txtCantidad.setText("");
        txtPrecioCompra.setText("");


    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed

        // 🔥 VALIDAR proveedor UNA SOLA VEZ
        if (cbProveedor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un proveedor válido");
            return;
        }

        // 🔥 VALIDAR que haya datos
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay productos para registrar");
            return;
        }

        ComprasDAO dao = new ComprasDAO();

        for (int i = 0; i < modelo.getRowCount(); i++) {

            Compra c = new Compra();

            c.setNombreProducto(modelo.getValueAt(i, 0).toString());
            c.setCantidad(Integer.parseInt(modelo.getValueAt(i, 1).toString()));
            c.setPrecioCompra(Double.parseDouble(modelo.getValueAt(i, 2).toString()));
            c.setProveedor(modelo.getValueAt(i, 3).toString());

            dao.insertarCompras(c);
        }

        JOptionPane.showMessageDialog(this, "Compra registrada");

        generarFacturaCompra();

        // 🔥 LIMPIAR TODO
        modelo.setRowCount(0);
        cbProveedor.setEnabled(true);
        cbProveedor.setSelectedIndex(0);

    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void generarFacturaCompra() {

        try {

            // ===== RUTA (ARREGLADA) =====
            String carpeta = "C:\\Users\\adoni\\OneDrive\\Documentos\\INGENIERIA\\ANÁLISIS Y DISEÑO DE SISTEMAS II\\RECIBOS PEDIDOS COMPRAS\\";
            File directorio = new File(carpeta);

            if (!directorio.exists()) {
                directorio.mkdirs();
            }

            String nombreArchivo = "Compra_" + System.currentTimeMillis() + ".pdf";
            String rutaCompleta = carpeta + nombreArchivo;

            Document document = new Document(PageSize.A4, 36, 36, 54, 36);
            PdfWriter.getInstance(document, new FileOutputStream(rutaCompleta));

            document.open();

            // ===== FUENTES =====
            Font tituloFont = new Font(Font.FontFamily.HELVETICA, 22, Font.BOLD);
            Font normalFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL);
            Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
            Font infoFont = new Font(Font.FontFamily.HELVETICA, 11, Font.NORMAL);

            // ===== ENCABEZADO =====
            Paragraph titulo = new Paragraph("MINISUPER ZONA AZUL", tituloFont);
            titulo.setAlignment(Element.ALIGN_CENTER);
            document.add(titulo);

            Font subtituloFont = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);

            Paragraph tipoDoc = new Paragraph("ORDEN DE PEDIDO DE COMPRA", subtituloFont);
            tipoDoc.setAlignment(Element.ALIGN_CENTER);
            document.add(tipoDoc);

            Paragraph info = new Paragraph(
                    "Cédula Jurídica: 3-101-748392\n"
                    + "Dirección:Nicoya,Guanacaste, Costa Rica\n"
                    + "Teléfono: 6358-1046\n",
                    infoFont
            );
            info.setAlignment(Element.ALIGN_CENTER);
            document.add(info);

            document.add(new Paragraph("\n"));

            Paragraph compraInfo = new Paragraph(
                    "Orden de Compra N°: " + System.currentTimeMillis() + "\n"
                    + "Fecha: " + java.time.LocalDateTime.now() + "\n"
                    + "Proveedor: " + cbProveedor.getSelectedItem() + "\n",
                    boldFont
            );
            document.add(compraInfo);

            document.add(new Paragraph("\n"));

            // ===== TABLA =====
            PdfPTable tabla = new PdfPTable(4);
            tabla.setWidthPercentage(100);
            tabla.setSpacingBefore(10f);
            tabla.setWidths(new float[]{4, 2, 2, 2});

            String[] headers = {"Producto", "Cantidad", "Precio Compra", "Total"};

            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(header, boldFont));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                tabla.addCell(cell);
            }

            DefaultTableModel modelo = (DefaultTableModel) tablaCompras.getModel();

            double totalGeneral = 0;

            for (int i = 0; i < modelo.getRowCount(); i++) {

                if (modelo.getValueAt(i, 0) == null) {
                    continue;
                }

                String producto = modelo.getValueAt(i, 0).toString();
                int cantidad = Integer.parseInt(modelo.getValueAt(i, 1).toString());
                double precio = Double.parseDouble(modelo.getValueAt(i, 2).toString());

                double total = cantidad * precio;
                totalGeneral += total;

                tabla.addCell(producto);
                tabla.addCell(String.valueOf(cantidad));
                tabla.addCell("₡ " + precio);
                tabla.addCell("₡ " + total);
            }

            document.add(tabla);
            document.add(new Paragraph("\n"));

            // ===== TOTAL =====
            Paragraph totalP = new Paragraph(
                    "TOTAL COMPRA: ₡ " + totalGeneral,
                    new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD)
            );
            totalP.setAlignment(Element.ALIGN_RIGHT);

            document.add(totalP);

            document.add(new Paragraph("\n\nDocumento generado para control interno", normalFont));

            document.close();

            // ===== ABRIR PDF =====
            File file = new File(rutaCompleta);

            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(file);
            }

            JOptionPane.showMessageDialog(this, "Compra generada en PDF correctamente");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar PDF de compra");
        }
    }
    private void tablaComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaComprasMouseClicked
        int fila = tablaCompras.getSelectedRow();

        if (fila >= 0) {
            // txtId.setText(tablaProveedores.getValueAt(fila, 0).toString());

            txtProducto.setText(tablaCompras.getValueAt(fila, 2).toString());

            txtCantidad.setText(tablaCompras.getValueAt(fila, 3).toString());

            txtPrecioCompra.setText(tablaCompras.getValueAt(fila, 4).toString());

            cbProveedor.setSelectedItem(tablaCompras.getValueAt(fila, 5).toString());

            // txtId.setEditable(false);
        }
    }//GEN-LAST:event_tablaComprasMouseClicked

    private void cbProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbProveedorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProveedorMouseClicked

    private void cbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProveedorActionPerformed

        if (!eventoActivado) {
            return;
        }

// 🔥 Evita que dispare al cargar
        if (cargandoProveedores) {
            return;
        }

        // 🔥 Evita que dispare si ya está bloqueado
        if (!cbProveedor.isEnabled()) {
            return;
        }

        // 🔥 Evita null
        if (cbProveedor.getSelectedIndex() == 0) {
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea realizar el pedido con este proveedor?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            cbProveedor.setEnabled(false); // 🔒 bloquear
        } else {
            cbProveedor.setSelectedIndex(0); // limpiar selección
        }
    }//GEN-LAST:event_cbProveedorActionPerformed

    private void limpiarCampos() {
        // txtId.setText("No es necesario insertar un ID");
        txtProducto.setText("");

        txtPrecioCompra.setText("");
        txtCantidad.setText("");
        cbProveedor.setSelectedIndex(0);
        //txtId.setForeground(Color.GRAY);

    }

    private void cargarTabla() {
        ComprasService service = new ComprasService();
        List<Compra> lista = service.listarCompra();

        DefaultTableModel modelo = (DefaultTableModel) tablaCompras.getModel();
        modelo.setRowCount(0); // limpia la tabla

        for (Compra c : lista) {
            modelo.addRow(new Object[]{
                c.getIdCompra(),
                c.getFecha(),
                c.getNombreProducto(),
                c.getCantidad(),
                c.getPrecioCompra(),
                c.getProveedor()
            }
            );
        }
    }

    private void cargarProveedores() {

        cargandoProveedores = true; // 🔥 evitar que dispare evento

        ProveedorService service = new ProveedorService();
        List<String> lista = service.listarNombres();

        cbProveedor.removeAllItems(); // limpiar antes

        cbProveedor.addItem("Seleccione proveedor");
        for (String nombre : lista) {
            cbProveedor.addItem(nombre);
        }

        cbProveedor.setSelectedIndex(0); // 👈 opcional: sin selección inicial

        cargandoProveedores = false; // 🔥 ya terminó de cargar
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnVolverMenú;
    private javax.swing.JComboBox<String> cbProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
