/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaModelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author adoni
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
      private Usuario usuarioLogueado; 
    public Reportes(Usuario usuario) {
        initComponents();
        this.usuarioLogueado = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        BtnProductos = new javax.swing.JButton();
        BtnLogin = new javax.swing.JButton();
        BtnClientes = new javax.swing.JButton();
        BtnProveedores = new javax.swing.JButton();
        BtnCompras = new javax.swing.JButton();
        BtnVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Icono MiniSuper.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("SELECCIONE EL ÍTEM A GENERAR REPORTE");

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("______________________________________________________________________________________________________________________________________________________________________________________________________________________________________");

        btnUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/btn usuarios.png"))); // NOI18N
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        BtnProductos.setBackground(new java.awt.Color(204, 204, 204));
        BtnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/btn productos.png"))); // NOI18N
        BtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProductosActionPerformed(evt);
            }
        });

        BtnLogin.setBackground(new java.awt.Color(255, 0, 0));
        BtnLogin.setFont(new java.awt.Font("Arial Black", 1, 26)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Volver al Menú");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        BtnClientes.setBackground(new java.awt.Color(204, 204, 204));
        BtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/btn Clientes.png"))); // NOI18N
        BtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClientesActionPerformed(evt);
            }
        });

        BtnProveedores.setBackground(new java.awt.Color(204, 204, 204));
        BtnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/btn Proveedores.png"))); // NOI18N
        BtnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProveedoresActionPerformed(evt);
            }
        });

        BtnCompras.setBackground(new java.awt.Color(204, 204, 204));
        BtnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Btn Compras.png"))); // NOI18N
        BtnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprasActionPerformed(evt);
            }
        });

        BtnVentas.setBackground(new java.awt.Color(204, 204, 204));
        BtnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/btn ventas.png"))); // NOI18N
        BtnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnProveedores, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnProductos)
                            .addComponent(BtnCompras))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnVentas)
                            .addComponent(BtnClientes))
                        .addGap(297, 297, 297))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnProductos)
                    .addComponent(btnUsuarios)
                    .addComponent(BtnClientes))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCompras)
                    .addComponent(BtnVentas)
                    .addComponent(BtnProveedores))
                .addGap(18, 18, 18)
                .addComponent(BtnLogin)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        int cri = JOptionPane.showConfirmDialog(null, "¿DESEA VOLVER AL MENÚ?");
        if (cri == 0) {
            Principal p;
            p = new Principal(usuarioLogueado);
            p.setVisible(true);
            dispose();

        }

    }//GEN-LAST:event_BtnLoginActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed

        int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE USUARIOS?");
        if (cri == 0) {

            JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void BtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProductosActionPerformed

        int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE PRODUCTOS?");
        if (cri == 0) {

            JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
        }

    }//GEN-LAST:event_BtnProductosActionPerformed

    private void BtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClientesActionPerformed

        int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE CLIENTES?");
        if (cri == 0) {

            JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
        }

    }//GEN-LAST:event_BtnClientesActionPerformed

    private void BtnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProveedoresActionPerformed

        int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE PROVEEDORES?");
        if (cri == 0) {

            JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
        }

    }//GEN-LAST:event_BtnProveedoresActionPerformed

    private void BtnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprasActionPerformed

        int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE COMPRAS?");
        if (cri == 0) {

            JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
        }

    }//GEN-LAST:event_BtnComprasActionPerformed

    private void BtnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasActionPerformed
        int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE VENTAS?");
        if (cri == 0) {

            JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
        }

    }//GEN-LAST:event_BtnVentasActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClientes;
    private javax.swing.JButton BtnCompras;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnProductos;
    private javax.swing.JButton BtnProveedores;
    private javax.swing.JButton BtnVentas;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
