/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaModelo.Usuario;
import CapaNegocio.ReporteService;
import javax.swing.JOptionPane;

/**
 *
 * @author adoni
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Usuario usuarioLogueado;

    public Reportes(Usuario usuario) {
        initComponents();
        this.usuarioLogueado = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnProductos = new javax.swing.JButton();
        BtnLogin = new javax.swing.JButton();
        BtnClientes = new javax.swing.JButton();
        BtnProveedores = new javax.swing.JButton();
        BtnCompras = new javax.swing.JButton();
        BtnVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Icono MiniSuper.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 1370, 140));

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("SELECCIONE EL ÍTEM A GENERAR REPORTE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 950, 43));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("______________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 1165, -1));

        BtnProductos.setBackground(new java.awt.Color(204, 204, 204));
        BtnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/btn productos.png"))); // NOI18N
        BtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(BtnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        BtnLogin.setBackground(new java.awt.Color(255, 0, 0));
        BtnLogin.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Volver al Menú");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 10, 270, -1));

        BtnClientes.setBackground(new java.awt.Color(204, 204, 204));
        BtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/btn Clientes.png"))); // NOI18N
        BtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(BtnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, -1, -1));

        BtnProveedores.setBackground(new java.awt.Color(204, 204, 204));
        BtnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/btn Proveedores.png"))); // NOI18N
        BtnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(BtnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        BtnCompras.setBackground(new java.awt.Color(204, 204, 204));
        BtnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Btn Compras.png"))); // NOI18N
        BtnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, -1));

        BtnVentas.setBackground(new java.awt.Color(204, 204, 204));
        BtnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/btn ventas.png"))); // NOI18N
        BtnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        int cri = JOptionPane.showConfirmDialog(null, "¿DESEA VOLVER AL MENÚ?");
        if (cri == 0) {
            Principal p;
            p = new Principal(usuarioLogueado);
            p.setVisible(true);
            dispose();

        }

    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProductosActionPerformed

        try {

            int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE PRODUCTOS?");
            if (cri == 0) {
                ReporteService reporteservice = new ReporteService();
                reporteservice.generarReporteProductos();
                JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar reporte");
        }

    }//GEN-LAST:event_BtnProductosActionPerformed

    private void BtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClientesActionPerformed

        try {

            int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE CLIENTES?");
            if (cri == 0) {

                ReporteService reporteService = new ReporteService();
                reporteService.generarReporteClientes();
                JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar el reporte");
        }

    }//GEN-LAST:event_BtnClientesActionPerformed

    private void BtnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProveedoresActionPerformed

        try {

            int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE PROVEEDORES?");
            if (cri == 0) {

                ReporteService reporteservice = new ReporteService();
                reporteservice.generarReporteProveedores();

                JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error al generar reporte");
        }

    }//GEN-LAST:event_BtnProveedoresActionPerformed

    private void BtnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprasActionPerformed

        try {

            int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE COMPRAS?");
            if (cri == 0) {

                ReporteService reporteService = new ReporteService();
                reporteService.generarReporteCompras();
                JOptionPane.showMessageDialog(this, "Reporte generado correctamente");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar reporte");
        }
    }//GEN-LAST:event_BtnComprasActionPerformed

    private void BtnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasActionPerformed
        try {

            int cri = JOptionPane.showConfirmDialog(null, "¿DESEA GENERAR UN REPORTE DE VENTAS?");
            if (cri == 0) {
                ReporteService reporte = new ReporteService();
                reporte.generarReporteVentas();
                JOptionPane.showMessageDialog(this, "Reporte generado correctamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar el reporte");
        }

    }//GEN-LAST:event_BtnVentasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClientes;
    private javax.swing.JButton BtnCompras;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnProductos;
    private javax.swing.JButton BtnProveedores;
    private javax.swing.JButton BtnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
