/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import java.io.File;
import CapaModelo.Producto;
import CapaModelo.Usuario;
import CapaNegocio.ProductoService;
import CapaNegocio.VentaService;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.FileOutputStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
//PRUEBA PARA VER SI CARGA BIEN 
// nueva prueba 

/**
 *
 * @author adoni
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Usuario usuarioLogueado;

    public Ventas(Usuario usuario) {
        initComponents();
        this.usuarioLogueado = usuario;
        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
        modelo.setRowCount(0);

        eventoEscritura();
        eventoLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        BtnModificar = new javax.swing.JButton();
        BtnVolverMenú = new javax.swing.JButton();
        BtnRegistrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnRegistrar1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Icono MiniSuper.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, 1370, 120));

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Gestión Ventas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 330, 43));

        jLabel3.setBackground(new java.awt.Color(0, 102, 204));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Nombre Producto: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 260, 30));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 245, 1090, -1));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Producto", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 920, 220));

        BtnModificar.setBackground(new java.awt.Color(0, 153, 51));
        BtnModificar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificar.setText("Confirmar Venta");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 630, 210, 50));

        BtnVolverMenú.setBackground(new java.awt.Color(255, 0, 0));
        BtnVolverMenú.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnVolverMenú.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolverMenú.setText("Volver a Menú");
        BtnVolverMenú.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverMenúActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVolverMenú, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 230, -1));

        BtnRegistrar.setBackground(new java.awt.Color(0, 204, 0));
        BtnRegistrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("+ Agregar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 310, 183, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 260, 35));

        lblTotal.setBackground(new java.awt.Color(0, 102, 204));
        lblTotal.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 102, 204));
        lblTotal.setText("0.00");
        lblTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, 220, 30));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 260, 35));

        jLabel9.setBackground(new java.awt.Color(0, 102, 204));
        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Cantidad: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, 30));

        jLabel10.setBackground(new java.awt.Color(0, 102, 204));
        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 204));
        jLabel10.setText("TOTAL: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 640, -1, 30));

        BtnRegistrar1.setBackground(new java.awt.Color(255, 0, 0));
        BtnRegistrar1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnRegistrar1.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar1.setText("- Eliminar");
        BtnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 183, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Logo Cantidad.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Logo código icono.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 40, 30));

        jLabel4.setBackground(new java.awt.Color(0, 102, 204));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Codigo Producto: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 250, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Imagenes/Logo productos icono.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 50, 50));
        jPanel1.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 260, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JPopupMenu popup = new JPopupMenu();
    JList listaUI = new JList();
    ProductoService servicio = new ProductoService();

    private void calcularTotal() {

        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
        BigDecimal totalGeneral = BigDecimal.ZERO;

        for (int i = 0; i < modelo.getRowCount(); i++) {

            Object precioObj = modelo.getValueAt(i, 3);

            if (precioObj != null) {
                BigDecimal precio = new BigDecimal(precioObj.toString());
                totalGeneral = totalGeneral.add(precio);
            }
        }

        lblTotal.setText(totalGeneral.toString());
    }

    private void buscar() {

        String texto = txtNombre.getText();

        if (texto.isEmpty()) {
            popup.setVisible(false);
            return;
        }

        List<Producto> lista = servicio.buscar(texto);

        mostrar(lista);
    }

    private void mostrar(List<Producto> productos) {

        DefaultListModel modelo = new DefaultListModel();

        for (Producto p : productos) {

            modelo.addElement(p.getNombre());

        }

        listaUI.setModel(modelo);

        popup.removeAll();

        popup.add(new JScrollPane(listaUI));

        popup.show(txtNombre, 0, txtNombre.getHeight());

    }

    private void cargarProducto(String nombre) {

        Producto p = servicio.buscarProductoPorNombre(nombre);

        if (p != null) {

            txtProducto.setText(p.getCodigo());
            txtNombre.setText(p.getNombre());

        }

    }

    private void eventoLista() {

        listaUI.addMouseListener(
                new java.awt.event.MouseAdapter() {

            public void mouseClicked(
                    java.awt.event.MouseEvent evt) {

                String nombre
                        = listaUI.getSelectedValue().toString();

                txtProducto.setText(nombre);

                cargarProducto(nombre);

                popup.setVisible(false);

            }

        });

    }

    private void eventoEscritura() {

        txtNombre.getDocument().addDocumentListener(
                new javax.swing.event.DocumentListener() {

            public void insertUpdate(
                    javax.swing.event.DocumentEvent e) {
                buscar();
            }

            public void removeUpdate(
                    javax.swing.event.DocumentEvent e) {
                buscar();
            }

            public void changedUpdate(
                    javax.swing.event.DocumentEvent e) {
                buscar();
            }

        });

    }

    private void BtnVolverMenúActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverMenúActionPerformed

        int filas = tablaVentas.getRowCount();

        int cri;

        if (filas > 0) {
            cri = JOptionPane.showConfirmDialog(
                    null,
                    "¿Seguro que desea volver al menú?\nSe eliminarán todos los productos agregados.",
                    "ADVERTENCIA",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            cri = JOptionPane.showConfirmDialog(
                    null,
                    "¿Desea volver al menú?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );
        }

        if (cri == JOptionPane.YES_OPTION) {
            Principal p = new Principal(usuarioLogueado);
            p.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_BtnVolverMenúActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();

        // Validar que haya productos
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay productos en la venta");
            return;
        }

        ProductoService productoService = new ProductoService();
        VentaService ventaService = new VentaService();

        try {

            for (int i = 0; i < modelo.getRowCount(); i++) {

                Object codObj = modelo.getValueAt(i, 0);
                Object nomObj = modelo.getValueAt(i, 1);
                Object cantObj = modelo.getValueAt(i, 2);
                Object precioObj = modelo.getValueAt(i, 3);

                // Validar que no haya celdas vacías
                if (codObj == null || nomObj == null || cantObj == null || precioObj == null) {
                    continue; // saltar fila defectuosa
                }

                String codigo = codObj.toString();
                String nombre = nomObj.toString();
                int cantidad = Integer.parseInt(cantObj.toString());
                BigDecimal precioTotal = new BigDecimal(precioObj.toString());

                // Guardar venta
                ventaService.guardarVenta(nombre, cantidad, precioTotal);

                // Descontar stock
                productoService.descontarStock(codigo, cantidad);
            }
            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Desea generar factura?",
                    "Factura",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion == JOptionPane.YES_OPTION) {
                generarFactura();
            }

            // Limpiar tabla después de confirmar
            modelo.setRowCount(0);
            lblTotal.setText("0.00");

            JOptionPane.showMessageDialog(this, "Venta realizada correctamente");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al procesar la venta");
        }

    }//GEN-LAST:event_BtnModificarActionPerformed

    private void generarFactura() {

        try {

            // ===== RUTA DONDE SE GUARDARÁ =====
            String carpeta = "C:\\Users\\adoni\\OneDrive\\Documentos\\INGENIERIA\\ANÁLISIS Y DISEÑO DE SISTEMAS II\\FACTURAS MINISUPER ZONA AZUL\\";
            File directorio = new File(carpeta);

            if (!directorio.exists()) {
                directorio.mkdirs();
            }

            String nombreArchivo = "Factura_" + System.currentTimeMillis() + ".pdf";
            String rutaCompleta = carpeta + nombreArchivo;

            Document document = new Document(PageSize.A4, 36, 36, 54, 36);
            PdfWriter.getInstance(document, new FileOutputStream(rutaCompleta));

            document.open();

            // ===== FUENTES =====
            Font tituloFont = new Font(Font.FontFamily.HELVETICA, 22, Font.BOLD);
            Font normalFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL);
            Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);

            // ===== ENCABEZADO =====
            Paragraph titulo = new Paragraph("MINI SUPER ZONA AZUL", tituloFont);
            titulo.setAlignment(Element.ALIGN_CENTER);
            document.add(titulo);

            Paragraph info = new Paragraph("Nicoya, Guanacaste\nTel: 6358-1046\n\n", normalFont);
            info.setAlignment(Element.ALIGN_CENTER);
            document.add(info);

            document.add(new Paragraph("Factura N°: " + System.currentTimeMillis(), boldFont));
            document.add(new Paragraph("Fecha: " + LocalDateTime.now(), normalFont));
            document.add(new Paragraph("\n"));

            // ===== TABLA =====
            PdfPTable tabla = new PdfPTable(5);
            tabla.setWidthPercentage(100);
            tabla.setSpacingBefore(10f);
            tabla.setWidths(new float[]{2, 4, 2, 2, 2});

            String[] headers = {"Código", "Producto", "Cantidad", "Precio Unit.", "Total"};

            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(header, boldFont));
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                tabla.addCell(cell);
            }

            DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();

            BigDecimal subtotal = BigDecimal.ZERO;

            for (int i = 0; i < modelo.getRowCount(); i++) {

                if (modelo.getValueAt(i, 0) == null) {
                    continue;
                }

                String codigo = modelo.getValueAt(i, 0).toString();
                String nombre = modelo.getValueAt(i, 1).toString();
                int cantidad = Integer.parseInt(modelo.getValueAt(i, 2).toString());
                BigDecimal total = new BigDecimal(modelo.getValueAt(i, 3).toString());

                BigDecimal precioUnitario = total.divide(new BigDecimal(cantidad), 2, RoundingMode.HALF_UP);

                subtotal = subtotal.add(total);

                tabla.addCell(codigo);
                tabla.addCell(nombre);
                tabla.addCell(String.valueOf(cantidad));
                tabla.addCell("₡ " + precioUnitario);
                tabla.addCell("₡ " + total);
            }

            document.add(tabla);
            document.add(new Paragraph("\n"));

            // ===== TOTALES =====
            BigDecimal iva = subtotal.multiply(new BigDecimal("0.13"));
            BigDecimal totalFinal = subtotal.add(iva);

            Paragraph subtotalP = new Paragraph("Subtotal: ₡ " + subtotal, normalFont);
            subtotalP.setAlignment(Element.ALIGN_RIGHT);

            Paragraph ivaP = new Paragraph("IVA (13%): ₡ " + iva, normalFont);
            ivaP.setAlignment(Element.ALIGN_RIGHT);

            Paragraph totalP = new Paragraph("TOTAL A PAGAR: ₡ " + totalFinal,
                    new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD));
            totalP.setAlignment(Element.ALIGN_RIGHT);

            document.add(subtotalP);
            document.add(ivaP);
            document.add(totalP);

            document.add(new Paragraph("\n\nGracias por su compra!", tituloFont));

            document.close();

            // ===== ABRIR AUTOMÁTICAMENTE =====
            File file = new File(rutaCompleta);

            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(file);
            }

            JOptionPane.showMessageDialog(this, "Factura generada y guardada\n");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar factura");
        }
    }
    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed

        if (txtNombre.getText().trim().isEmpty() || txtCantidad.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un producto y una cantidad");
            return;
        }

        String producto = txtNombre.getText(); // ahora es nombre
        int cantidad;

        try {
            cantidad = Integer.parseInt(txtCantidad.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número, no letras");
            txtCantidad.setText("");
            return;
        }

        ProductoService service = new ProductoService();

// 🔹 ahora busca por nombre
        Producto p = service.buscarProductoPorNombre(producto);

        if (p == null) {
            JOptionPane.showMessageDialog(this, "Producto no existe");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();

        boolean encontrado = false;

        for (int i = 0; i < modelo.getRowCount(); i++) {

            String codigoTabla = modelo.getValueAt(i, 0).toString();

            if (codigoTabla.equals(p.getCodigo())) {

                int cantidadActual = Integer.parseInt(modelo.getValueAt(i, 2).toString());
                int nuevaCantidad = cantidadActual + cantidad;

                if (nuevaCantidad > p.getCantidadEnStock()) {
                    JOptionPane.showMessageDialog(this, "Stock insuficiente");
                    return;
                }

                if (nuevaCantidad == p.getCantidadEnStock()) {
                    JOptionPane.showMessageDialog(this, "Se ha agotado el stock de este producto");
                }

                BigDecimal nuevoTotal
                        = p.getPrecio().multiply(new BigDecimal(nuevaCantidad));

                modelo.setValueAt(nuevaCantidad, i, 2);
                modelo.setValueAt(nuevoTotal, i, 3);

                encontrado = true;
                break;
            }
        }

        if (!encontrado) {

            if (cantidad > p.getCantidadEnStock()) {
                JOptionPane.showMessageDialog(this, "Stock insuficiente");
                return;
            }

            if (cantidad == p.getCantidadEnStock()) {
                JOptionPane.showMessageDialog(this, "Se ha agotado el stock de este producto");
            }

            BigDecimal precioTotal
                    = p.getPrecio().multiply(new BigDecimal(cantidad));

            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNombre(),
                cantidad,
                precioTotal
            });
        }

        calcularTotal();

        txtNombre.setText("");
        txtCantidad.setText("");
        txtProducto.setText("");
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void actualizarTotal() {

        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
        BigDecimal totalVenta = BigDecimal.ZERO;

        for (int i = 0; i < modelo.getRowCount(); i++) {

            if (modelo.getValueAt(i, 3) != null) {
                BigDecimal totalFila = new BigDecimal(modelo.getValueAt(i, 3).toString());
                totalVenta = totalVenta.add(totalFila);
            }
        }

        lblTotal.setText("" + totalVenta);
    }
    private void BtnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrar1ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();

// Verificar si hay una fila seleccionada
        int filaSeleccionada = tablaVentas.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla para eliminar");
            return;
        }
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar este producto?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            modelo.removeRow(filaSeleccionada);
            actualizarTotal();
        }
    }//GEN-LAST:event_BtnRegistrar1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnRegistrar1;
    private javax.swing.JButton BtnVolverMenú;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
